
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tanisha
 */
public class main_screen extends javax.swing.JFrame {

    /**
     * Creates new form main_screen
     */
    public main_screen() {
        initComponents();
    date.setText(java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbalance = new javax.swing.JButton();
        bankstat = new javax.swing.JButton();
        addmon = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkbalance.setBackground(new java.awt.Color(153, 153, 255));
        checkbalance.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        checkbalance.setForeground(new java.awt.Color(153, 0, 51));
        checkbalance.setText("Check Balance");
        checkbalance.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        checkbalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalanceActionPerformed(evt);
            }
        });

        bankstat.setBackground(new java.awt.Color(255, 204, 204));
        bankstat.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bankstat.setForeground(new java.awt.Color(153, 0, 51));
        bankstat.setText("Bank statements");
        bankstat.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bankstat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bankstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankstatActionPerformed(evt);
            }
        });

        addmon.setBackground(new java.awt.Color(153, 255, 204));
        addmon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        addmon.setForeground(new java.awt.Color(153, 0, 51));
        addmon.setText("Add money");
        addmon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        addmon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmonActionPerformed(evt);
            }
        });

        withdraw.setBackground(new java.awt.Color(204, 204, 204));
        withdraw.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        withdraw.setForeground(new java.awt.Color(153, 0, 51));
        withdraw.setText("Withdraw amount");
        withdraw.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        withdraw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        withdraw.setOpaque(false);
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 153));
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIMANSHU\\Downloads\\axis.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        jLabel1.setOpaque(true);

        date.setBackground(new java.awt.Color(204, 204, 255));
        date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(204, 0, 102));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(addmon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bankstat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbalance)
                    .addComponent(bankstat))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addmon)
                    .addComponent(withdraw))
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        checkbalance.getAccessibleContext().setAccessibleParent(checkbalance);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public JFrame frame;
    private void checkbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalanceActionPerformed
        f2=new cbalance();
        this.setVisible(false);
        f2.setVisible(true);
    }//GEN-LAST:event_checkbalanceActionPerformed
cbalance f2;
withdraw f3;
bankstat f4;
    private void bankstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankstatActionPerformed
          f4=new bankstat();
        f4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bankstatActionPerformed
eg f1;
    private void addmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmonActionPerformed
        f1=new eg();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addmonActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        f3=new withdraw();
        this.setVisible(false);
        f3.setVisible(true);
    }//GEN-LAST:event_withdrawActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame =new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"DO you want to exit","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmon;
    private javax.swing.JButton bankstat;
    private javax.swing.JButton checkbalance;
    private javax.swing.JLabel date;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
